Netcentric/fe-build

- .github/workflows/release.yml
> ci: disable dry-run

- docs/tasks.md
> fix: remove broken image

- README.md
> docs: add quickstart example

- docs/tasks.md
Fixes #
nc-fe-build is for this prroject not hecore :)
> Fix wrong bin names

- utils/generateEntries.js
> fix: dist path replace

- utils/merge.js
Bugfix (utils)
Allow to use boolean values in the .febuild config file
> bugfix(utils): merge boolean values

- .github/workflows/ci.yml
- .releaserc
> fix: add package.json to automated release updates

- package-lock.json
- package.json
> #37 update node-sass

- .github/workflows/release.yml
- .releaserc
- cli/index.js
- index.js
- package.json
> fix: change cli path

- .github/workflows/release.yml
> fix: update missing changelog plugin version

- LICENSE
- docs/CODE_OF_CONDUCT.md
> docs: updates company name

- .github/workflows/codeql-analysis.yml
> build: updates action to latest version

- package-lock.json
- package.json
> build: fixes high severity vulnerabilities

- .github/workflows/manual-release.yml
manual release matches regular release workflow
Fixes #
> build: manual release matches regular release workflow

- package.json
> #91 Updated preinstall script to create missing folders if needed

- .github/workflows/ci.yml
- .github/workflows/manual-release.yml
- .github/workflows/release.yml
- package-lock.json
Attempts to fix the manual release action
> build: updates build

- .github/workflows/ci.yml
> #97 update pipeline to run npm install on windows

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/manual-release.yml
- .github/workflows/release.yml
- docs/CONTRIBUTING.md
> ci: fix manual release

- package-lock.json
- package.json
- utils/runStylelint.js
BREAKING CHANGE: Update stylelint to v16
Fixes #108
> BREAKING CHANGE: Update stylelint to v16

- config/babel.config.js
- docs/configuration.md
> fix(config): change package namespace in babel.config exclude property

- .npmignore
- package-lock.json
- tasks/webpack.test.js
- utils/renderPostcss.js
- utils/renderSass.js
> fix: #112 - update source maps for new sass version
